### ISSUE TITLE
Experiment modeling

### ISSUE THREAD

**Issue by zxenia** [bento-platform/katsu#100]
Some points that arose during the discussion about Experiment modeling

1. Decide on required fields for Experiment class
2. ` molecule_ontology` and `experiment_ontology`: ArrayField of JSONFields, validation of each json against ONTOLOGY_CLASS schema

3. Other things to think about:

- Metadata about how the library was prepared (e.g. what kind of sequencer was used?)
- Results of the experiment: VCF files, signal files, GenPipes computed metrics, feature specific annotations

**Comment by dbujold** [comment]
For point 3, interestingly, while sequencing technology isn't part of the IHEC-required metadata, it is mandatory for submitting data to the EGA. So definitely, I'd find a way to add it somewhere.

**Comment by zxenia** [comment]
@dbujold how about these attributes [here](https://github.com/IHEC/ihec-ecosystems/blob/master/docs/metadata/1.1/Ihec_metadata_specification.md#wgbs-note-this-is-a-new-name-to-be-used-instead-of-bisulfite-seq-), is it essential to add it to data model? or it's ok to store as json?

**Comment by romgrk** [comment]
@zxenia forgot to ask but I've added an `id varchar(200)` field on the experiment model, is this ok? How do we plan to distinguish experiments?

**Comment by zxenia** [comment]
@romgrk Yes,  it's ok. We have unique ids for all our data elements.
If there are unique identifiers for experiments in legacy data that we import than we use them, if not then we can always generate UUID (or set that primary key would be generated for db).
