### ISSUE TITLE
The Dashboard statistics

### ISSUE THREAD

**Issue by zxenia** [bento-platform/katsu#106]
We should distinguish between phenotypic data and reference resources used for data annotation.

**Phenotypic data dashboard**

- Number of Individuals
- Number of Biosamples
- Number of PhenotypiucFeatures
- Number of Phenopackets
- Number of unique Diseases: need to filter queryset for Disease and get the sum of unique ids (the id from the term)

Would be nice to have:

- How many related Variants we have overall;
- The number on related HTS files (I know we are not yet sure how the HTS file workflow will work)

**Annotation statistics**

Resource:
- number of unique resources used to describe the data (id - e.g. 'uniprot' - the duplicates are not allowed, so it should be just the number of all resources);
- a list of all ids + name - so the user can check it right away

**Comment by davidlougheed** [comment]
@zxenia for phenotypic features, should we pool them together or count phenopackets and biosamples in separate counters? leaning towards the latter

**Comment by zxenia** [comment]
@davidlougheed I think for the dashboard we should pool them together - it's better for the general overview of the data. We can add like a note saying it's for both biosamples and phenopackets.

**Comment by zxenia** [comment]
implemented
