### ISSUE TITLE
Elasticsearch indexing should be user enabled instead of automatic

### ISSUE THREAD

**Issue by shaikh-rashid** [bento-platform/katsu#178]
Katsu currently automatically tries to use elasticsearch to store FHIR data. If this is feature is optional, it would be nice to have it be off by default and user enabled via settings.py and/or environment variable. Furthermore, the elasticsearch instance that katsu uses to index FHIR models should be configurable in order to isolate it from other elasticsearch instances.

**Comment by zxenia** [comment]
Implemented in the latest release.
