### ISSUE TITLE
Table summary endpoint

### ISSUE THREAD

**Issue by davidlougheed** [bento-platform/katsu#85]
* Sex breakdown IN THE TABLE
* Age groups (histogram) IN THE TABLE
* Diseases present IN THE TABLE
* Number of biosamples IN THE TABLE
* Number of individuals IN THE TABLE
* Biosamples per (phenopacket or individual) IN THE TABLE

**Comment by davidlougheed** [comment]
partially complete

**Comment by zxenia** [comment]
implemented
